stages:
  - test

default:
  tags:
    - gambrero

pytest_job:
  stage: test
  image: python:3.10
  before_script:
    - pip install -r requirements.txt
  script:
    - pytest --alluredir=./allure-results